#!/bin/bash
# This is a helper script for buildroot type builds. Export:
#  TARGET_DIR, BUILD_DIR, PYTHON_VERSION_MAJOR, PYTHON_VERSION
# variables, and specify UWSGICONFIG_PYTHONCONFIG to point to this script.

if [ -z "$TARGET_DIR" ]; then
    echo "Please specify TARGET_DIR environment variable" >&2
    exit 1
fi

if [ -z "$BUILD_DIR" ]; then
    echo "Please specify BUILD_DIR environment variable" >&2
    exit 1
fi

if [ -z "$PYTHON_VERSION_MAJOR" ]; then
    echo "Please specify PYTHON_VERSION_MAJOR environment variable" >&2
    exit 1
fi

if [ -z "$PYTHON_VERSION" ]; then
    echo "Please specify PYTHON_VERSION environment variable" >&2
    exit 1
fi


if [ "$1" == "--includes" ]; then
    echo "\
-I${BUILD_DIR}/python-${PYTHON_VERSION}/Include \
-I${TARGET_DIR}/usr/lib/python${PYTHON_VERSION_MAJOR}/config"
    exit 0
elif [ "$1" == "--ldflags" ]; then
    echo "-lpython${PYTHON_VERSION_MAJOR}"
    exit 0
fi

exit 1
